# Generated by Django 3.2.6 on 2021-09-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='so',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
