# Generated by Django 3.2.6 on 2021-09-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0002_auto_20210912_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
