# Generated by Django 3.2.6 on 2021-09-20 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0002_alter_supplier_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podetail',
            name='Qty_order',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Quantity order must greater or equal than 0')]),
        ),
        migrations.AlterField(
            model_name='sodetail',
            name='Qty_order',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Quantity order must greater than 0')]),
        ),
    ]
