# Generated by Django 3.2.6 on 2021-08-23 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0004_po'),
    ]

    operations = [
        migrations.CreateModel(
            name='SO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty_total', models.IntegerField(default=0, null=True)),
                ('closed_date', models.DateTimeField(null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('add_who', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='so_add_who', to=settings.AUTH_USER_MODEL)),
                ('edit_who', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='so_edit_who', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms.supplier')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
