# Generated by Django 3.2.6 on 2021-09-22 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0004_alter_item_qty_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podetailtemp',
            name='PO',
        ),
        migrations.RemoveField(
            model_name='podetailtemp',
            name='item',
        ),
        migrations.DeleteModel(
            name='ItemTemp',
        ),
        migrations.DeleteModel(
            name='PODetailTemp',
        ),
    ]
