# Generated by Django 3.2.6 on 2021-09-12 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0005_alter_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='Qty_total',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Quantity total at least 1 CASE')]),
        ),
        migrations.AlterField(
            model_name='so',
            name='Qty_total',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Quantity total at least 1 CASE')]),
        ),
    ]
