# Generated by Django 3.2.6 on 2021-09-22 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0005_auto_20210922_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='po',
            name='Qty_total',
        ),
        migrations.RemoveField(
            model_name='so',
            name='Qty_total',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Qty_just',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1, 'khong duoc duoi 1 CASE')]),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Qty_order',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1, 'khong duoc duoi 1 CASE')]),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Qty_receipt',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1, 'khong duoc duoi 1 CASE')]),
        ),
        migrations.AlterField(
            model_name='receiptdetail',
            name='Qty_just',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1, 'khong duoc duoi 1 CASE')]),
        ),
        migrations.AlterField(
            model_name='receiptdetail',
            name='Qty_order',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1, 'khong duoc duoi 1 CASE')]),
        ),
        migrations.AlterField(
            model_name='receiptdetail',
            name='Qty_receipt',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1, 'khong duoc duoi 1 CASE')]),
        ),
    ]
