# Generated by Django 3.2.6 on 2021-08-23 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0006_podetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SODetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty_order', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('SO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.so')),
                ('item', models.ManyToManyField(to='wms.Item')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
