# Generated by Django 3.2.6 on 2021-09-22 03:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0006_auto_20210922_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='po',
            name='active',
        ),
        migrations.RemoveField(
            model_name='podetail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='so',
            name='active',
        ),
        migrations.RemoveField(
            model_name='sodetail',
            name='description',
        ),
        migrations.AddField(
            model_name='po',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='so',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Qty_total',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0, 'Quantity total must greater than 0')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='mu_case',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Quantity MU/CASE must greater than or equal')]),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Qty_just',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1, 'Quantity just must greater than 0')]),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Qty_order',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1, 'Quantity order must greater than 0')]),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Qty_receipt',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1, 'Quantity just must greater than 0')]),
        ),
        migrations.AlterField(
            model_name='receiptdetail',
            name='Qty_just',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1, 'Quantity just must greater than 0')]),
        ),
        migrations.AlterField(
            model_name='receiptdetail',
            name='Qty_order',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1, 'Quantity order must greater than 0')]),
        ),
        migrations.AlterField(
            model_name='receiptdetail',
            name='Qty_receipt',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1, 'Quantity just must greater than 0')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'ADMIN'), (1, 'USER'), (2, 'SUPPLIER')], default=0),
        ),
    ]
