# Generated by Django 3.2.6 on 2021-09-12 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0006_auto_20210912_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='closed_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 12, 16, 26, 27, 205953)),
        ),
        migrations.AlterField(
            model_name='so',
            name='closed_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 12, 16, 26, 27, 205953)),
        ),
    ]
