# Generated by Django 3.2.6 on 2021-08-23 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0007_sodetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('SO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.so')),
                ('add_who', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_add_who', to=settings.AUTH_USER_MODEL)),
                ('edit_who', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_edit_who', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('PO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.po')),
                ('add_who', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_add_who', to=settings.AUTH_USER_MODEL)),
                ('edit_who', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_edit_who', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceiptDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty_order', models.IntegerField(default=0, null=True)),
                ('Qty_just', models.IntegerField(default=0, null=True)),
                ('Qty_receipt', models.IntegerField(default=0, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('item', models.ManyToManyField(to='wms.Item')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.receipt')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty_order', models.IntegerField(default=0, null=True)),
                ('Qty_just', models.IntegerField(default=0, null=True)),
                ('Qty_receipt', models.IntegerField(default=0, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('item', models.ManyToManyField(to='wms.Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.order')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
