# Generated by Django 3.2.6 on 2021-09-22 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0008_alter_podetail_qty_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podetail',
            name='Qty_order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Quantity order must greater or equal than 1')]),
        ),
        migrations.AlterField(
            model_name='sodetail',
            name='Qty_order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Quantity order must greater or equal than 1')]),
        ),
    ]
