# Generated by Django 3.2.6 on 2021-08-23 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0009_auto_20210823_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlocation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.item'),
        ),
    ]
