# Generated by Django 3.2.6 on 2021-09-25 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0009_auto_20210922_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='Qty_just',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='Qty_order',
        ),
        migrations.RemoveField(
            model_name='receiptdetail',
            name='Qty_just',
        ),
        migrations.RemoveField(
            model_name='receiptdetail',
            name='Qty_order',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Qty_receipt',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0, 'Quantity just must greater than or equal 0')]),
        ),
        migrations.AlterField(
            model_name='receiptdetail',
            name='Qty_receipt',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0, 'Quantity just must greater than or equal 0')]),
        ),
    ]
