# Generated by Django 3.2.6 on 2021-09-26 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0010_auto_20210925_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetail', to='wms.order'),
        ),
        migrations.AlterField(
            model_name='receiptdetail',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiptdetail', to='wms.receipt'),
        ),
    ]
