# Generated by Django 3.2.6 on 2021-09-13 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0010_auto_20210912_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='closed_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 13, 21, 42, 40, 755651)),
        ),
        migrations.AlterField(
            model_name='so',
            name='closed_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 13, 21, 42, 40, 755651)),
        ),
    ]
