# Generated by Django 3.2.6 on 2021-09-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0012_auto_20210929_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='closed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='effective_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='so',
            name='closed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='so',
            name='effective_date',
            field=models.DateField(),
        ),
    ]
