# Generated by Django 3.2.6 on 2021-09-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0013_auto_20210929_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='po',
            name='closed_date',
        ),
        migrations.RemoveField(
            model_name='so',
            name='closed_date',
        ),
    ]
