# Generated by Django 3.2.6 on 2021-09-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0014_auto_20210913_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowlocation',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
