# Generated by Django 3.2.6 on 2021-09-30 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0014_auto_20210929_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfcolumn',
            name='row_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wms.rowlocation'),
        ),
        migrations.AlterField(
            model_name='shelffloor',
            name='row_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wms.rowlocation'),
        ),
    ]
