# Generated by Django 3.2.6 on 2021-09-30 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0015_auto_20211001_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfcolumn',
            name='row_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.rowlocation'),
        ),
        migrations.AlterField(
            model_name='shelffloor',
            name='row_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.rowlocation'),
        ),
    ]
