# Generated by Django 3.2.6 on 2021-09-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0015_rowlocation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expire_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='production_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='itemtemp',
            name='expire_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='itemtemp',
            name='production_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='edit_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='add_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='closed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='edit_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='effective_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='add_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='edit_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='so',
            name='add_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='so',
            name='closed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='so',
            name='edit_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='so',
            name='effective_date',
            field=models.DateField(),
        ),
    ]
