# Generated by Django 3.2.6 on 2021-10-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0016_auto_20211001_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowlocation',
            name='name',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='shelfcolumn',
            unique_together={('column', 'row_location')},
        ),
        migrations.AlterUniqueTogether(
            name='shelffloor',
            unique_together={('floor', 'row_location')},
        ),
    ]
