# Generated by Django 3.2.6 on 2021-10-01 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0018_alter_location_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.location'),
        ),
    ]
