# Generated by Django 3.2.6 on 2021-10-01 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0019_alter_itemlocation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Qty_total',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0, 'Quantity total must greater or equal than 0')]),
        ),
    ]
