# Generated by Django 3.2.6 on 2021-10-01 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0020_alter_item_qty_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_location', to='wms.location'),
        ),
    ]
