# Generated by Django 3.2.6 on 2021-10-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0024_exportview_importview'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportview',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='importview',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
