# Generated by Django 3.2.6 on 2021-10-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0025_auto_20211003_2103'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='importview',
            unique_together={('PO', 'item', 'location')},
        ),
        migrations.DeleteModel(
            name='ExportView',
        ),
    ]
