# Generated by Django 3.2.6 on 2021-10-05 15:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0026_auto_20211005_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Quantity just must greater than or equal 0')])),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('SO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_view', to='wms.so')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_loc_export_view', to='wms.location')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_view', to='wms.item')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_loc_export_view', to='wms.location')),
            ],
            options={
                'unique_together': {('SO', 'item', 'from_location', 'to_location')},
            },
        ),
    ]
