# Generated by Django 3.2.6 on 2021-10-05 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0027_exportview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportview',
            name='to_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_loc_export_view', to='wms.location'),
        ),
    ]
