# Generated by Django 3.2.6 on 2021-10-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0029_alter_exportview_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='po',
            name='description',
        ),
        migrations.RemoveField(
            model_name='so',
            name='description',
        ),
        migrations.AlterField(
            model_name='po',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'PENDING'), (1, 'ACCEPTED'), (3, 'FAILED'), (0, 'DONE'), (4, 'IMPORTED')], default=2),
        ),
        migrations.AlterField(
            model_name='so',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'PENDING'), (1, 'ACCEPTED'), (3, 'FAILED'), (0, 'DONE'), (4, 'EXPORTED')], default=2),
        ),
    ]
