# Generated by Django 3.2.6 on 2021-10-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0030_auto_20211020_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['id']},
        ),
    ]
